### ISSUE TITLE
"I had some trouble with that: Failed to save embeddings"

### ISSUE THREAD

**Issue by mtbhuskies** [squarecat/doc-buddy#5]
Any hints on why the telegram bot is telling me "I had some trouble with that: Failed to save embeddings" I've double and triple checked my Pinecone API Key, seems like it's getting hung up there, as it's not making it to my S3 bucket.

**Comment by Jivings** [comment]
Hey! Where did you deploy? My usual problem was that there was a mismatch between the API key environment variables. Note that the embeddings project needs your OpenAI key too, but the variable name is a bit different 🤦‍♂️

**Comment by mtbhuskies** [comment]
Thanks for the reply. Deploying to DigitalOcean, following the guide exactly as written. Can you elaborate on "the embeddings project needs your OpenAI key too"? That's not registering for me. Maybe more coffee it needed.

**Comment by Jivings** [comment]
Yep, once you've deployed (if using the deploy button on the README), then you'll end up with one DO App with two services running in it. One of them is used to manage the embeddings that OpenAI creates from your pdf documents. 

You'll see the [environment variables](https://github.com/squarecat/doc-buddy/blob/main/.do/deploy.template.yaml) are different for each project, but the OpenAI API key is only subtly different. One is called `OPEN_AI_KEY` and the other is called `OPENAI_API_KEY`. Sorry about that 😅

I also noticed a typo in the deploy script, so maybe try deploying with the button again and see if it works okay now!
