### ISSUE TITLE
Two quick questions 

### ISSUE THREAD

**Issue by larspeet** [squarecat/doc-buddy#6]
First. Is it possible to upload PDFs in bulk, and then direct the bot to digest the repository?  Loading one at a time via chat may take a while. 

Second. I’m leaning toward trying this on Discord rather than Telegram. Any tips/advice? 

Hope you’re well.

**Comment by Jivings** [comment]
Hey! It's possible if you change the code 😅

I think if you bulk upload them to telegram it should work though.

I don't know anything about discord sorry! But the chat part is quite basic, it's just in `chat.js`. If you wanted to make it more platform agnostic then feel free to submit a PR!
